### ISSUE TITLE
Why feat_recon_loss is 0?

### ISSUE THREAD

**Issue by xiaoyihit** [JunwenBai/c-gmvae#2]
Why feat_recon_loss is 0?
In the paper, 'The reconstruction loss is a standard negative log-likelihood with decoder parameters θ,'
However, it seems that feat_recon_loss is fixed to 0. in the implementation.
Could you kindly explain the reason behind this?

**Comment by JunwenBai** [comment]
Thx for the interest in our paper. In practice, we found adding the feat recon only brings a little gain while consuming much more memory. Reconstruction essentially serves as a regularization. You should be able to achieve roughly the same performance without the reconstruction, using the script provided in the repo. But feel free to add and tune the reconstruction regularization as you need, which should be straightforward.
Another consideration that is worth exploring is the tradeoff between the reconstruction and contrastive loss. I suspect the strict reconstruction may hamper the flexibility of contrastive learning a bit, regarding the representation learning. A good tradeoff should give even better performance.
