### ISSUE TITLE
other datasets

### ISSUE THREAD

**Issue by geek-APTX4869** [JunwenBai/c-gmvae#5]
Dear author：
  如何在其它数据集上训练模型呢，想学习一下

**Comment by JunwenBai** [comment]
Pls check out https://github.com/JunwenBai/C-GMVAE/tree/master/data/mirflickr to see how to create and formalize a similar dataset. You can also see the explanation [here](https://github.com/JunwenBai/MPVAE?tab=readme-ov-file#data-format).
